// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn63MbFuilO7tWUGH4Ex7PbVTOxh1HIfY',
    appId: '1:338520165593:web:79e84de1cf34cb625b82c8',
    messagingSenderId: '338520165593',
    projectId: 'apptcc-ec1ec',
    authDomain: 'apptcc-ec1ec.firebaseapp.com',
    storageBucket: 'apptcc-ec1ec.appspot.com',
    measurementId: 'G-PPXKP1J5CX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOBh3ZKJfZUMyG0KTGCtCLxfk8uDKoV3k',
    appId: '1:338520165593:android:10702b1c2bfdce775b82c8',
    messagingSenderId: '338520165593',
    projectId: 'apptcc-ec1ec',
    storageBucket: 'apptcc-ec1ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6RiEDLGXGT5iQVEE81XZAlssUXwcgzuA',
    appId: '1:338520165593:ios:877744ec9e1c4b6b5b82c8',
    messagingSenderId: '338520165593',
    projectId: 'apptcc-ec1ec',
    storageBucket: 'apptcc-ec1ec.appspot.com',
    iosClientId:
        '338520165593-mus3qdvgipso6epu3ocskobagoc1haum.apps.googleusercontent.com',
    iosBundleId: 'com.example.apptcc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6RiEDLGXGT5iQVEE81XZAlssUXwcgzuA',
    appId: '1:338520165593:ios:877744ec9e1c4b6b5b82c8',
    messagingSenderId: '338520165593',
    projectId: 'apptcc-ec1ec',
    storageBucket: 'apptcc-ec1ec.appspot.com',
    iosClientId:
        '338520165593-mus3qdvgipso6epu3ocskobagoc1haum.apps.googleusercontent.com',
    iosBundleId: 'com.example.apptcc',
  );
}
